apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: registry.io/wordpress:1.2
        resources:
          requests:
            cpu: "100m"
            memory: "10Mi"
          limits:
            cpu: "200m"
            memory: "50Mi"
        env:
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-cred
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-cred
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_HOST
           
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-content
          mountPath: /var/www/html/wordpress/wp-content
      volumes:
      - name: wordpress-content
        persistentVolumeClaim:
         claimName: wordpress-content-pvc
